noirstore:
    debug: false
    sellpercent: 5 # percentage to be taken off sell prices.
    tradedelay: -1 # How long before a player can trade again, in milliseconds (1s = 1000ms).
    mysql:
        username:
        password:
        host: localhost
        port: 3306
        database:
        prefix: store_

